### ISSUE TITLE
System Messages blocked

### ISSUE THREAD

**Issue by Sortsmudsker** [GryllsAddons/TurtleZoneCount#1]
Hello!
I think this might have happened after an update, but I can no longer see system messages.
"/roll" or when my friends come online is no longer shown.

**Comment by mafima** [comment]
happens to me too

**Comment by GryllsAddons** [comment]
Thanks, I've updated this and changed the functionality to work with the new /who limit. 
Please let me know if this has resolved the issue or if you have any other feedback.
